import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly } from 'workbox-strategies';

declare let self: any;

// Precache assets generated by Vite PWA
precacheAndRoute(self.__WB_MANIFEST);

const PERSISTED_SHARE_KEY = 'goondrop-pending-share';

// Handle Web Share Target (Level 2 - files!) from the iOS Share Sheet
self.addEventListener('message', (event: any) => {
  const data = event.data;
  if (!data) return;
  if (data.meta !== 'share-target-handler') return;
  
  // Navigate the app window to handle the share
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients: any[]) => {
      if (windowClients.length > 0) {
        return windowClients[0].navigate(data.url);
      }
      return self.clients.openWindow(data.url);
    })
  );
});

// Handle POST share target requests (files + text)
self.addEventListener('fetch', (event: any) => {
  const url = new URL(event.request.url);

  // Only handle POST requests to our root (share target action)
  if (event.request.method !== 'POST') return;
  if (url.pathname !== '/' && url.pathname !== '/index.html') return;

  // If there's no multipart body, it's not from the share target
  const hasContentType = event.request.headers.has('content-type');
  if (!hasContentType || !event.request.headers.get('content-type')!.includes('multipart/form-data')) return;

  event.respondWith(
    event.request.formData().then(async (formData: any) => {
      // Extract text/URL params
      const title = formData.get('title') || '';
      const text = formData.get('text') || '';
      const urlParam = formData.get('url') || '';
      const files = formData.getAll('files') || [];

      // Persist the share data for the app to consume
      const sharePayload: any = { title: String(title), text: String(text), url: String(urlParam) };

      // Batch-upload each shared file directly to the Windows PC
      if (files.length > 0) {
        sharePayload.fileCount = files.length;
        sharePayload.fileStatuses = [];

        for (const file of files) {
          try {
            const uploadForm = new FormData();
            uploadForm.append('file', file, file.name);

            const resp = await fetch('/api/drop', { method: 'POST', body: uploadForm });
            if (resp.ok) {
              sharePayload.fileStatuses.push({ name: file.name, status: 'success' });
            } else {
              sharePayload.fileStatuses.push({ name: file.name, status: 'error', error: 'Server rejected upload' });
            }
          } catch (err: any) {
            sharePayload.fileStatuses.push({ name: file.name, status: 'error', error: err.message });
          }
        }
      }
      // Handle text / url share (if no files)
      else if (text || urlParam) {
        try {
          const isUrl = String(urlParam).startsWith('http') || String(text).startsWith('http');
          if (isUrl) {
            const target = String(urlParam || text);
            await fetch('/api/handoff', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ url: target })
            });
          } else {
            await fetch('/api/clipboard', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ text: String(text || title || '') })
            });
          }
        } catch (err: any) {
          sharePayload.uploadError = err.message;
        }
      }

      // Store in IndexedDB-like storage for the app
      const localStorageKey = 'goondrop_last_share';
      try {
        localStorage.setItem(localStorageKey, JSON.stringify(sharePayload));
      } catch { }

      // Redirect to the main app page which will read the share data
      return Response.redirect('/?share=received', 303);
    }).catch(() => {
      // Fallback: redirect to home
      return Response.redirect('/', 303);
    })
  );
});

// Handle Push Notifications
self.addEventListener('push', (event: any) => {
  if (!event.data) return;

  try {
    const payload = event.data.json();
    const title = payload.title || 'Goon Drop';
    const options = {
      body: payload.body || 'New synchronization update',
      icon: payload.icon || '/icons/icon-192.svg',
      badge: '/icons/icon-192.svg',
      data: payload,
      tag: payload.type || 'goondrop-notification'
    };

    event.waitUntil(
      self.registration.showNotification(title, options)
    );
  } catch (err) {
    console.error('[SW] Push payload parse failed:', err);
    // Fallback notification
    event.waitUntil(
      self.registration.showNotification('Goon Drop', {
        body: 'You have a new sync update!',
        icon: '/icons/icon-192.svg'
      })
    );
  }
});

// Handle notification clicks
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();

  const payload = event.notification.data;
  const action = event.action;

  if (action) {
    // User clicked a specific action button
    event.waitUntil(
      fetch('/api/push/action', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: action,
          deviceId: payload.deviceId,
          fileId: payload.fileId,
          payload: payload
        })
      }).then(() => {
        // After action, we can optionally open the app
        return self.clients.openWindow('/');
      })
    );
  } else {
    // User clicked the notification body
    const urlToOpen = payload?.url || '/';
    event.waitUntil(
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients: any[]) => {
        if (windowClients.length > 0) {
          return windowClients[0].focus();
        }
        return self.clients.openWindow(urlToOpen);
      })
    );
  }
});

// Generic API routing (network only) for Goon Drop APIs
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkOnly()
);