import Foundation

/// Centralized configuration shared between the main Goon Drop app and the Share Sheet extension.
/// Uses App Groups (`group.com.goondrop.app`) so preferences set in the app are immediately
/// accessible to the iOS Share Sheet extension.
public class SharedConfig: ObservableObject {
    public static let shared = SharedConfig()
    
    public static let appGroupName = "group.com.goondrop.app"
    
    private var defaults: UserDefaults {
        return UserDefaults(suiteName: SharedConfig.appGroupName) ?? UserDefaults.standard
    }
    
    private let keyServerHost = "goondrop_server_host"
    private let keyServerPort = "goondrop_server_port"
    private let keyUseHttps   = "goondrop_use_https"
    private let keyPairingCode = "goondrop_pairing_code"
    private let keyAutoSend    = "goondrop_auto_send"
    
    @Published public var serverHost: String {
        didSet {
            defaults.set(serverHost.trimmingCharacters(in: .whitespacesAndNewlines), forKey: keyServerHost)
        }
    }
    
    @Published public var serverPort: Int {
        didSet {
            defaults.set(serverPort, forKey: keyServerPort)
        }
    }
    
    @Published public var useHttps: Bool {
        didSet {
            defaults.set(useHttps, forKey: keyUseHttps)
        }
    }
    
    @Published public var pairingCode: String {
        didSet {
            defaults.set(pairingCode.trimmingCharacters(in: .whitespacesAndNewlines), forKey: keyPairingCode)
        }
    }
    
    @Published public var autoSend: Bool {
        didSet {
            defaults.set(autoSend, forKey: keyAutoSend)
        }
    }
    
    private init() {
        let defs = UserDefaults(suiteName: SharedConfig.appGroupName) ?? UserDefaults.standard
        let host = defs.string(forKey: keyServerHost) ?? "192.168.1.100"
        let port = defs.integer(forKey: keyServerPort)
        let https = defs.object(forKey: keyUseHttps) as? Bool ?? true
        let code = defs.string(forKey: keyPairingCode) ?? ""
        let auto = defs.object(forKey: keyAutoSend) as? Bool ?? true
        
        self.serverHost = host
        self.serverPort = port > 0 ? port : 3942
        self.useHttps = https
        self.pairingCode = code
        self.autoSend = auto
    }
    
    public var baseURLString: String {
        let scheme = useHttps ? "https" : "http"
        return "\(scheme)://\(serverHost):\(serverPort)"
    }
    
    public var apiDropURL: URL? {
        URL(string: "\(baseURLString)/api/drop")
    }
    
    public var apiHandoffURL: URL? {
        URL(string: "\(baseURLString)/api/handoff")
    }
    
    public var apiClipboardURL: URL? {
        URL(string: "\(baseURLString)/api/clipboard")
    }
    
    public var apiHealthURL: URL? {
        URL(string: "\(baseURLString)/api/health")
    }
    
    /// Create a URLSession configured to trust local self-signed certificates for LAN transfer
    public static func makeLANSession() -> URLSession {
        let config = URLSessionConfiguration.default
        config.timeoutIntervalForRequest = 30
        config.timeoutIntervalForResource = 300
        return URLSession(configuration: config, delegate: LANTrustSessionDelegate(), delegateQueue: nil)
    }
}

/// URLSession delegate that accepts local self-signed SSL certificates generated by Goon Drop
public class LANTrustSessionDelegate: NSObject, URLSessionDelegate {
    public func urlSession(
        _ session: URLSession,
        didReceive challenge: URLAuthenticationChallenge,
        completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void
    ) {
        if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust,
           let serverTrust = challenge.protectionSpace.serverTrust {
            // Local network self-signed certificate trust
            completionHandler(.useCredential, URLCredential(trust: serverTrust))
        } else {
            completionHandler(.performDefaultHandling, nil)
        }
    }
}
